spring.application.name=hospital
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_hospitalario
spring.datasource.username=postgres
spring.datasource.password=postgres

logging.level.org.springframework.jdbc.core=DEBUG